server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:twoje_haslo}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# --- DODANE ZMIENNE DO INTEGRACJI ---
app:
  keycloak:
    internal-url: ${KEYCLOAK_INTERNAL_URL}
    external-url: ${KEYCLOAK_URL}
  analytics:
    url: ${ANALYTICS_SERVICE_URL}
