spring:
  application:
    name: catalog-service
  datasource:
    url: ${CATALOG_DB_URL}
    username: ${CATALOG_DB_USER}
    password: ${CATALOG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/library-system/protocol/openid-connect/certs
aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET_NAME}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
server:
  port: 8081
